### ISSUE TITLE
Add more Markdown shortcuts in the editor toolbar

### ISSUE THREAD

**Issue by msoultanidis** [msoultanidis/quillnote#1]
Add shortcuts for:

- Links
- Images
- Tables (needs a special table builder dialog)

**Comment by foxonfox** [comment]
Shortcuts like:

- Highlight
- Underline
- Up/Down arrow (to go to beginning and end of note) will be useful when editing long notes.

**Comment by msoultanidis** [comment]
> Shortcuts like:
> 
>     * Highlight
> 
>     * Underline
> 
>     * Up/Down arrow (to go to beginning and end of note) will be useful when editing long notes.

Markdown does not support the first two. Up & down arrows sound useful.

**Comment by msoultanidis** [comment]
Table, hyperlink & image shortcuts implemented in bc5565d52c8745d700ea3a76ebec1b62e13ebb93

**Comment by foxonfox** [comment]
> Markdown does not support the first two

Then how come the current markdown app I use support it?  

![Image](https://user-images.githubusercontent.com/56470153/124364204-8ec0c780-dc5d-11eb-8cc0-c95e72daa1b2.jpg)

I will really miss the highlight function. It's very useful.

**Comment by msoultanidis** [comment]
> > Markdown does not support the first two
> 
> Then how come the current markdown app I use support it?

AFAIK both Underline & Highlight are not in the official Markdown standard and were most likely additions by the developer.

**Comment by msoultanidis** [comment]
Up & down buttons added in 027570b4e23ca7aa3012a03d6649017748dd4d57
