### ISSUE TITLE
Bug: voice note automatically plays after putting down phone call 

### ISSUE THREAD

**Issue by laraib07** [msoultanidis/quillnote#11]
I created a voice note to test the app, then deleted it.  Now when I put down a phone call , the voive note plays automatically.
To make sure its not device specific, I made my friend test the same and he faced the same bug.
We both using android 11.

**Comment by msoultanidis** [comment]
Does this happen after recording or afte rclicking on the recorded clip and playing it? 

I will look into it, thanks for the report.

**Comment by laraib07** [comment]
I played it after recording it.
I will now check if it occur for recording i haven't played.
