### ISSUE TITLE
Major Crashing Bug

### ISSUE THREAD

**Issue by odolitus** [msoultanidis/quillnote#110]
My app is now continuously crashing due to what I believe is an unrecognizable character in the note when it was saved. It appeared as a new line but could not be deleted. As soon as I exited the note and it saved, the app crashed. 

Also, I would like to know if there is there a way to retrieve my data so that I can use it in the meantime? I don't want to have to delete all of my notes, and my last backup was a long time ago.

**Comment by msoultanidis** [comment]
I'm sorry to hear that :(

Do you remember any characters that might have caused that?
Were you using markdown? 

There is a way to edit the database file from your PC and push it back to the device but it's a bit risky and I don't recommend it:
1. Install ADB
2. Connect your device 
3. Enable USB Debugging from the Developer Options
4. Run this command inside a terminal from your PC: `adb -d shell 'run-as org.qosp.notes cat /data/data/org.qosp.notes/databases/notes_database' > notes_database`

Now there's a file `notes_database`. Open it with a hex editor (not Notepad as that will mess up the encoding) and search for the note content that you think might have caused the crash. Change it and save the file.

Force stop Quillnote and run:
1. `adb push notes_database /data/local/tmp`
2. `adb shell run-as org.qosp.notes cp /data/local/tmp/notes_database databases`
3. `adb shell run-as org.qosp.notes rm databases/notes_database-shm`
4. `adb shell run-as org.qosp.notes rm databases/notes_database-wal`

It worked on my phone but do it at your own risk.

**Comment by odolitus** [comment]
I should have given more information from the get-go, my bad.

I was copying multiple lines from a normal note with markdown enabled (no markdown in the text copied) and pasted it into a checklist in a single item, which is when I noticed the new line that was unable to be deleted.

Thank you for the instructions, I will try this when I'm home. If I can isolate the problem note I will try to provide a copy to you so that you can troubleshoot it. Just using my prior knowledge about code, I feel like it's trying to display the character in the preview before you open the note, but because it's unrecognized it just crashes.
A possible temporary fix might be to, after a crash, temporarily disable the note preview so that all you see is the title, and then ask the user if they would like to revert it back.

**Comment by odolitus** [comment]
I managed to create a backup of the app using ADB and unpacked it and was able to get the data, here's the content of the list item that I'm fairly certain was the cause of the perpetual crashing minus the actual thing it said:
`{"id":6,"content":"\n\nMessage content redacted","isDone":false}`

**Comment by msoultanidis** [comment]
I'm afraid I can't do anything with that :(
I tested list items that start with multiple newline characters but it works fine.
