### ISSUE TITLE
Bug: Select all

### ISSUE THREAD

**Issue by solowav3** [msoultanidis/quillnote#117]
Hey there! Thank you very much for taking your time and creating this beautiful .md note-taking app!

Here is the bug I've stumbled upon - select all notes works recursively, meaning I could select already selected notes again:
[video 1](https://drive.google.com/file/d/1G1eWQE4tIHon71Itm9RazKXE41Mv4fO7/view?usp=sharing)

and if I preselect some of the notes but then change my mind and want to select all, it counts on top of those preselected:
[video 2](https://drive.google.com/file/d/1okHZFn7FtAZH0UcUL661G0_LljKBnchQ/view?usp=sharing)

**Comment by msoultanidis** [comment]
Thanks for the report!

**Comment by msoultanidis** [comment]
Fixed in 528564aadf3b81636f6fecc4045f5a14e10507dd!
