### ISSUE TITLE
Option : Save File Attachments to a Directory

### ISSUE THREAD

**Issue by yant0** [msoultanidis/quillnote#120]
I removed files from my internal and some attachments in Quillnote is not showing right.

Feature :
- Option to save attachments in a directory
- internal storage / removable storage
- deleting original files wont be problem anymore

**Comment by msoultanidis** [comment]
This is intended. If the user wants to delete a file from his device then it should NOT stay inside app storage.
As a work around, choose the "Backup everything" setting, export the note and then restore it. That will move the file inside Quillnote's app storage.
