### ISSUE TITLE
[FR] Title Color

### ISSUE THREAD

**Issue by yant0** [msoultanidis/quillnote#16]
![Imagepipe_1](https://user-images.githubusercontent.com/80298071/124062304-6dd94780-d9bb-11eb-8997-171293a783fc.jpg)

**Comment by msoultanidis** [comment]
That's weird. 

- What is your device's ROM/OS? 
- Is it like this all the time or did you do anything that caused the title to become green? If it's the latter, please reply with some steps I can follow to reproduce this.

Thanks.

**Comment by yant0** [comment]
Im sorry if its unclear its a feature request 😅

**Comment by msoultanidis** [comment]
Oh, okay! I don't think this is needed at the moment as you can already change the background color of the notes if you want to make them distinct. 

Issue closed for now.
