### ISSUE TITLE
Import existing notebook

### ISSUE THREAD

**Issue by shawn1thompson** [msoultanidis/quillnote#18]
Is there a way to import an existing Markdown notebook?

**Comment by msoultanidis** [comment]
What do you mean by Markdown notebook?

**Comment by shawn1thompson** [comment]
I mean a collection of notes written in Markdown. Currently, I'm using Markor and I can point it to my notebook directory. I love what I can do with the app, but have never really liked the UI. Yours has much more aesthetic appeal in my opinion.

**Comment by msoultanidis** [comment]
That's a good idea, it is going to be really useful for people who want to migrate their notes to Quillnote. I will definitely look into it!

**Comment by msoultanidis** [comment]
Related to https://github.com/msoultanidis/quillnote/issues/9
