### ISSUE TITLE
Crashes when opened

### ISSUE THREAD

**Issue by teasin951** [msoultanidis/quillnote#180]
This was an amazing app. I loved using it but with the new update, when I try to open it, it crashes. You can still long hold and create a note but the main screen does not want to load. I tried downgrading the app on F-droid and that resulted in a few errors and the loss of all of my notes... I wanted to setup my nextcloud but I could not get hold of a RPi and now I don't have anything apart from one or two notes I have backed up just to test the function.

Edit: I've just tried to load the backup and it makes the app crash when I go to the main screen again. I presume the upgrade has made a function obosolete.

**Comment by msoultanidis** [comment]
This has been fixed in 7882cbf9f1d71fc9d80a99590a0498e95a3fb245 and should be on its way to F-Droid.
