### ISSUE TITLE
Automatic bullet points

### ISSUE THREAD

**Issue by foxonfox** [msoultanidis/quillnote#27]
The markdown editor recognises hyphen '-' as bullet point. But after creating one bullet point and press enter it does not create the next bullet point automatically. It would have been nice if this feature could be implemented.

**Comment by msoultanidis** [comment]
Yeah, this should definitely be implemented for both bullet point lists and numbered lists.

**Comment by msoultanidis** [comment]
Implemented in bc5565d52c8745d700ea3a76ebec1b62e13ebb93
