### ISSUE TITLE
Keyboard not shown automatically after pressing back

### ISSUE THREAD

**Issue by PavinWu** [msoultanidis/quillnote#44]
Using v1.2.0 on Android 11 (Pixel 4a).

To reproduce:
- kill app from background if it's opened, then open it again.
- press plus button to create a new note. Keyboard appears
- press Android back button to hide keyboard, then back again to main page
- Create a new note again. Keyboard is not shown.

However, keyboard is shown after going back to the launcher, then come back to app again.

**Comment by msoultanidis** [comment]
I will look into it, thanks.

**Comment by msoultanidis** [comment]
Okay, I reproduced it and I managed to fix it in 2920d403d04e7b91a496cd4a8284800c705847ad.
