### ISSUE TITLE
Empty preview after pressing Back, animations sluggish

### ISSUE THREAD

**Issue by ltGuillaume** [msoultanidis/quillnote#46]
1. Pressed + to create a note
2. Converted to list via menu
3. Entered a title and some list items and pressed Back (hardware button, if it matters)

Result: the new note got shown first (sorted descending by creation date), but the preview was empty, except for a single checkbox.

The actual preview was created only after reopening the note and pressing back again.

I also see that the animations used in the app are very costly and seem to be sluggisch quite often. Perhaps this could be optimized or optionally disabled for older devices?

**Comment by msoultanidis** [comment]
I will look into it, thanks.

**Comment by msoultanidis** [comment]
I reproduced it but it only happens sometimes on my phone. Is is the same for you as well?

**Comment by msoultanidis** [comment]
Preview bug fixed in 4ee9b17205f7302beec1675aba855faf2c318de5
