### ISSUE TITLE
App does not ask or get storage permission

### ISSUE THREAD

**Issue by natanael9o** [msoultanidis/quillnote#53]
I use a Oneplus 8 pro and when I try to create a backup, load an attachment or restore. Basicly everything that has to have storage permission the app crashes. 

When I took a look at the permissions the app has gotten the only alternative is for the mic and nothing else is even showing up. 

So the root to the problem is probably the app never asking for storage permission and because it never ask that and think it has it the app crashes. 

This is probably an easy fix and a needed one, because beside this issue, it is the best note app with functions that no other note app that I have found has atleast that is open source.

**Comment by msoultanidis** [comment]
I can't reproduce this crash from any of my phones. Is it happening persistently?

**Comment by natanael9o** [comment]
https://user-images.githubusercontent.com/87022397/124617172-03228300-de77-11eb-8067-8affc7be4df4.mp4

It is happening persistently. I am on stock but rooted with magisk.

**Comment by natanael9o** [comment]
> I can't reproduce this crash from any of my phones. Is it happening persistently? Also are you using stock or custom ROM?
Do your phones have the storage permission for this app? I will try with another phone and see if the same thing happens, otherwise it is a device specific problem, which I do not hope.

**Comment by msoultanidis** [comment]
That's weird. 
- Do you have enabled any Magisk modules that interfere with the Storage Access Framework?
- Is system's file picker working for other apps?

Also it would really help me if you posted the stack trace you see in Logcat. Since you are rooted you can easily see that with an app like Logcat Reader from F-Droid.

**Comment by natanael9o** [comment]
It works on my other phone. So I will close this issue. Thanks for the help.
