### ISSUE TITLE
[Help] How to Insert an Image?

### ISSUE THREAD

**Issue by alphanerdgen** [msoultanidis/quillnote#73]
I don't know what to enter in the 'Image Path' field. If you do then please let me know.

![Insert Image](https://user-images.githubusercontent.com/83120103/125164359-71d14a80-e1af-11eb-921b-706d522ddb1a.png)

**Comment by msoultanidis** [comment]
In the "Image path" field you insert the URL/path of the image, for example "https://qosp.org/static/media/logo_round.345bdcc8.png"

**Comment by alphanerdgen** [comment]
Oh, so it's not for adding an image in the device storage to a note. All right. Thought it'd make the image appear in-line instead of on top of a note.

Anyway, thanks for the reply. Closing it.
