### ISSUE TITLE
Change the Font?

### ISSUE THREAD

**Issue by alphanerdgen** [msoultanidis/quillnote#77]
![Quillnote Font](https://user-images.githubusercontent.com/83120103/125166242-50c12780-e1b8-11eb-97bd-a93ad0f10975.png)

![Notally Font](https://user-images.githubusercontent.com/83120103/125166247-574f9f00-e1b8-11eb-9e11-79eeb9de0c68.png)

**Comment by msoultanidis** [comment]
No plans to change font currently. It could happen though in a version with a major visual overhaul. For now, issue closed.
