### ISSUE TITLE
Feature Request : Undo/Redo

### ISSUE THREAD

**Issue by swarnendumaiti** [msoultanidis/quillnote#87]
If I'm not wrong, I do not find a Undo/Redo button. I often write long notes, and if I mistakenly erase many lines, I couldn't bring it back.

Such an option is really needed in Quillnote.

**Comment by afmbsr** [comment]
+1

**Comment by msoultanidis** [comment]
Next update (v.1.4.0) will feature the ability to undo & redo text changes.

**Comment by Kodmod** [comment]
For those who don't know: [FlorisBoard](https://f-droid.org/packages/dev.patrickgold.florisboard/) has the undo/redo feature at the keyboard level, so it works anywhere. It's probably the best FOSS keyboard right now.
